import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/eu.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg" 

export default function Home() {
  return (
    <>
      <Head>
        <title>cleiton-bp</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={profilePic}
                alt="cleiton-bp"
                className="w-full h-auto"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Creating visions into reality."
                className="!text-6xl !text-left"
              />
              <p className="my-4 text-base font-medium">
                As a full-stack developer, I am dedicated to transforming ideas
                into innovative applications. Explore my projects and articles
              </p>
              <div className="flex items-center self-start mt2">
                <Link
                  className="flex items-center bg-dark text-light p-2 px-6 rounded-lg 
										text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark"
                  target={"_blank"}
                  href="https://cleiton-bp.github.io/curriculo/"
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  className="ml-4 text-lg font-medium capitalize text-dark underline hover:drop-shadow-md"
                  target={"_blank"}
                  href="https://wa.me/5551996908049"
                  subject="subject text"
                >
                  Contact 
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />

        <div className="absolute right-8 bottom-8 inline-block w-24">
          <Image src={lightBulb} alt="cleiton-bp" className="w-full h-auto"/>
        </div>
      </main>
    </>
  );
}
