import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/eu.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>cleiton-bp</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="cleiton-bp"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="
                  (max-width: 768px) 100vw,
                  (max-width: 1200px) 50vw,
                  50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Creating visions into reality."
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a full-stack developer, I am dedicated to transforming ideas
                into innovative applications. Explore my projects and articles
              </p>
              <div className="flex items-center self-start mt2 lg:self-center">
                <Link
                  className="flex items-center bg-dark text-light p-2 px-6 rounded-lg 
										text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid 
                    border-transparent hover:border-dark dark:bg-light dark:text-dark 
                    hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:text-base"
                  target={"_blank"}
                  href="https://cleiton-bp.github.io/curriculo/"
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  className="ml-4 text-lg font-medium capitalize text-dark underline hover:drop-shadow-md dark:text-light md:text-base"
                  target={"_blank"}
                  href="https://wa.me/5551996908049"
                  subject="subject text"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />

        <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image src={lightBulb} alt="cleiton-bp" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
