import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/eu.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import { useLanguage } from "@/i18n/LanguageContext";
import { motion, useAnimationControls, useMotionValue, useSpring, useTransform } from "framer-motion";
import { useEffect } from "react";

export default function Home() {
  const { t } = useLanguage();

  // Cursor position normalized to [-0.5, 0.5] around the viewport center.
  const mvX = useMotionValue(0);
  const mvY = useMotionValue(0);

  // Only the aura behind the character parallaxes with the cursor — the
  // character itself stays fixed.
  const glowX = useSpring(useTransform(mvX, [-0.5, 0.5], [28, -28]), { stiffness: 70, damping: 20 });
  const glowY = useSpring(useTransform(mvY, [-0.5, 0.5], [28, -28]), { stiffness: 70, damping: 20 });

  // Light-bulb click burst.
  const flashControls = useAnimationControls();

  useEffect(() => {
    const onMove = (e) => {
      mvX.set(e.clientX / window.innerWidth - 0.5);
      mvY.set(e.clientY / window.innerHeight - 0.5);
    };
    window.addEventListener("mousemove", onMove);
    return () => window.removeEventListener("mousemove", onMove);
  }, [mvX, mvY]);

  return (
    <>
      <Head>
        <title>cleiton-bp</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="relative flex items-center text-dark w-full min-h-screen overflow-hidden dark:text-light">
        {/* Ambient drifting blobs for depth */}
        <motion.div
          aria-hidden
          animate={{ x: [0, 40, 0], y: [0, -30, 0] }}
          transition={{ duration: 16, repeat: Infinity, ease: "easeInOut" }}
          className="pointer-events-none absolute -left-20 top-1/3 -z-10 h-72 w-72 rounded-full bg-primary/10 blur-3xl dark:bg-primaryDark/10"
        />
        <motion.div
          aria-hidden
          animate={{ x: [0, -50, 0], y: [0, 40, 0] }}
          transition={{ duration: 20, repeat: Infinity, ease: "easeInOut" }}
          className="pointer-events-none absolute right-0 bottom-10 -z-10 h-80 w-80 rounded-full bg-primaryDark/10 blur-3xl dark:bg-primary/10"
        />

        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <motion.div
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.7, ease: "easeOut" }}
                className="relative w-[76%] mx-auto mt-16 lg:hidden md:inline-block md:mt-0 md:w-full"
              >
                {/* neon aura — visible glow, but starting below the top so it never bleeds behind the header */}
                <motion.div
                  aria-hidden
                  style={{ x: glowX, y: glowY }}
                  className="pointer-events-none absolute inset-x-6 -bottom-6 top-1/4 -z-10 rounded-full bg-primary/20 blur-3xl dark:bg-primaryDark/25"
                />
                {/* character — fixed, does not react to the mouse */}
                <Image
                  src={profilePic}
                  alt="cleiton-bp"
                  className="w-full h-auto"
                  priority
                  sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
                />
              </motion.div>
            </div>

            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text={t("hero.title")}
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <motion.p
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.9, ease: "easeOut" }}
                className="my-4 text-base font-medium md:text-sm sm:text-xs"
              >
                {t("hero.subtitle")}
              </motion.p>
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 1.1, ease: "easeOut" }}
                className="flex items-center self-start mt-2 lg:self-center"
              >
                <Link
                  className="flex items-center bg-dark text-light p-2 px-6 rounded-lg
											text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid
                    border-transparent hover:border-dark dark:bg-light dark:text-dark
                    hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:text-base
                    transition-colors duration-300 hover:shadow-[0_0_24px_-6px_rgba(0,0,255,0.5)] dark:hover:shadow-[0_0_24px_-6px_rgba(88,230,217,0.6)]"
                  target={"_blank"}
                  href="https://cleiton-bp.github.io/curriculo/"
                >
                  {t("hero.resume")} <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  className="ml-4 text-lg font-medium capitalize text-dark underline hover:drop-shadow-md dark:text-light md:text-base"
                  target={"_blank"}
                  href="https://wa.me/5551996908049"
                  subject="subject text"
                >
                  {t("hero.contact")}
                </Link>
              </motion.div>
            </div>
          </div>
        </Layout>

        <HireMe />

        <motion.div
          className="group absolute right-8 bottom-40 inline-block w-24 cursor-pointer md:hidden"
          whileHover={{ scale: 1.15, rotate: [0, -10, 10, -6, 6, 0] }}
          whileTap={{ scale: 0.9 }}
          onClick={() =>
            flashControls.start({
              opacity: [0, 0.95, 0],
              scale: [0.4, 1.8, 2.3],
              transition: { duration: 0.55, ease: "easeOut" },
            })
          }
          transition={{ duration: 0.6, ease: "easeInOut" }}
        >
          {/* glow that "turns on" at hover */}
          <span
            aria-hidden
            className="pointer-events-none absolute -inset-2 -z-10 rounded-full bg-yellow-300/0 blur-2xl transition-colors duration-300 group-hover:bg-yellow-300/70"
          />
          {/* burst of light on click */}
          <motion.span
            aria-hidden
            initial={{ opacity: 0 }}
            animate={flashControls}
            className="pointer-events-none absolute -inset-4 -z-10 rounded-full bg-yellow-200 blur-2xl"
          />
          <Image
            src={lightBulb}
            alt="cleiton-bp"
            className="w-full h-auto transition-[filter] duration-300 group-hover:[filter:drop-shadow(0_0_12px_rgba(253,224,71,0.95))]"
          />
        </motion.div>
      </main>
    </>
  );
}
